### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by bgetting** [FareHarbor/fareharbor-docs#2]
I noticed in the [webhooks documentation](https://github.com/FareHarbor/fareharbor-docs/blob/master/external-api/webhooks.md) that "bookings created via the API" can trigger a webhook.

What about bookings that are not created via the API?

**Comment by stevebeyatte** [comment]
@bgetting all bookings actions, regardless of the channel they are created with, can trigger webhooks. You can contact your Account Manager to get everything set up. Thanks!
