### ISSUE TITLE
Retrieve all bookings for a given date

### ISSUE THREAD

**Issue by weeg** [FareHarbor/fareharbor-docs#27]
Hi!

Is there any way to retrieve all bookings for a given date? 

As I can seen there is no API endpoint for this at the moment, however it would be very useful, and the FareHarbor API could have been used for other than just OTA bookings.

**Comment by bryanknauber** [comment]
Hey @weeg! Can you connect with your account manager (or your client's account manager) about this? That will get your request through our usual new feature channels and make sure we have your use case in mind. Thanks!
