### ISSUE TITLE
Item Detail end point is not available 

### ISSUE THREAD

**Issue by pravint4f** [FareHarbor/fareharbor-docs#7]
Hi

In docs i can't find out about item details api and some other information 

can you please share it ?

1) item details end point like if i want information for specific product than how can i retrieve that ?
2) if one company has more items , is there pagination available , how many items will be listed on per page and what specific search request param for that ? 

Thank You!

**Comment by bryanknauber** [comment]
Hi there! You should be able to get to what you're looking for with the [items endpoint](https://github.com/FareHarbor/fareharbor-docs/blob/master/external-api/endpoints.md#items). If you don't have a contact at FareHarbor yet email us at support@fareharbor.com and we'll get you in touch with the right folks.

Thanks!
